Feature/can mark processed message complete when exception occurred
Scooletz/QueueBatch pull request #16
Opened 2019-01-09 08:55 UTC by jeremy001181

Implementation for #15

2019-01-09 09:07 UTC, jeremy001181 commented
@Scooletz As you suggested, I added a new attribute to allow consumer to choose whether to fail or success batch as whole, not sure if the name is ideal, you might want to come up with a different name; 

When the attribute `SuccessOrFailAsBatch` set true (which is the default value), it works exactly same as before, which means the `batch.MarkAsProcessed(message)` doesn't take effect on individual message level, if one of messages in the same batch causes exception, they will have to set `SuccessOrFailAsBatch` to `false`, to truly make this `batch.MarkAsProcessed(message)` work, which is a bit confusing;

2019-01-19 08:27 UTC, Scooletz requested changes
Awesome work 🎉 If you could fix a few minors, I'll merge it and release.

2019-01-19 08:27 UTC, Scooletz commented on src/QueueBatch.Tests/BaseTest.cs
> +                var content = JsonConvert.SerializeObject(new { id = Guid.NewGuid().ToString("N") });
Do we need JSON in here for testing? Why instead of deserializing JSON, you'd try to `Guid.Parse` ?

2019-01-19 08:27 UTC, Scooletz commented on src/QueueBatch.Tests/IntegrationTests.cs
> +                return Task.Run(async () =>
What's the reason for starting it as a task? Do you want to test concurrency as well? This test could just loop over messages, marking them as processed only when they are added to the output. This would preserve the semantics of what you're testing here, wouldn't it? If not, could you elaborate on it?

2019-01-19 08:27 UTC, Scooletz commented on src/QueueBatch.Tests/IntegrationTests.cs
> +            public static async Task Do(
Is it autoformatting applied here? I can see that some signatures were changed in a similar way.

2019-01-19 08:27 UTC, Scooletz commented on src/QueueBatch/Impl/Listener.cs
> +        private readonly bool successOrFailAsBatch;
```suggestion
        readonly bool successOrFailAsBatch;
```

2019-01-19 08:27 UTC, Scooletz commented on src/QueueBatch/QueueBatchTriggerAttribute.cs
> +        public bool SuccessOrFailAsBatch { get; set; } = true;
Nice. With this default we can ship it as a minor.

2019-01-19 08:27 UTC, Scooletz commented on src/QueueBatch.Tests/Helpers.cs
> +
```suggestion

```

2019-01-19 08:27 UTC, Scooletz commented on README.md
> +With `SuccessOrFailAsBatch` set to `false`, you can also acknowledge only some of the messages. The rest, will be retried in a similar manner to the regural `[QueueTrigger]`
Nice!

2019-01-19 08:28 UTC, Scooletz commented
@jeremy001181 I see that there might be some confusion, but let's ship it as a minor as you provided and maybe, a set of breaking changes can be accumulated to get 2.0.

2019-01-19 09:39 UTC, jeremy001181 commented
No problems I will make the changes accordingly this weekend

Thanks

On Sat, 19 Jan 2019, 8:27 am Szymon Kulec <notifications@github.com wrote:

> *@Scooletz* requested changes on this pull request.
>
> Awesome work 🎉 If you could fix a few minors, I'll merge it and release.
> ------------------------------
>
> In src/QueueBatch.Tests/BaseTest.cs
> <https://github.com/Scooletz/QueueBatch/pull/16#discussion_r249238485>:
>
> > @@ -47,7 +48,7 @@ protected async Task<List<string>> SendUnique(int count = 1)
>
>              var list = new List<string>();
>
>              for (var i = 0; i < count; i++)
>
>              {
>
> -                var content = Guid.NewGuid().ToString("N");
>
> +                var content = JsonConvert.SerializeObject(new { id = Guid.NewGuid().ToString("N") });
>
>
> Do we need JSON in here for testing? Why instead of deserializing JSON,
> you'd try to Guid.Parse ?
> ------------------------------
>
> In src/QueueBatch.Tests/IntegrationTests.cs
> <https://github.com/Scooletz/QueueBatch/pull/16#discussion_r249238537>:
>
> > +        public class SuccessOrFailAsBatchFalse
>
> +        {
>
> +            public static async Task Do(
>
> +                  [QueueBatchTrigger(InputQueue, MaxBackOffInSeconds = 1, SuccessOrFailAsBatch = false)] IMessageBatch batch
>
> +                , [Queue(OutputQueue)] CloudQueue output)
>
> +            {
>
> +                await SomeMessageInBatchCauseException(batch, output);
>
> +            }
>
> +        }
>
> +
>
> +        private static async Task SomeMessageInBatchCauseException(IMessageBatch batch, CloudQueue output)
>
> +        {
>
> +            var messages = batch.Messages.ToList();
>
> +            var tasks = messages.Select((m, i) =>
>
> +            {
>
> +                return Task.Run(async () =>
>
>
> What's the reason for starting it as a task? Do you want to test
> concurrency as well? This test could just loop over messages, marking them
> as processed only when they are added to the output. This would preserve
> the semantics of what you're testing here, wouldn't it? If not, could you
> elaborate on it?
> ------------------------------
>
> In src/QueueBatch.Tests/IntegrationTests.cs
> <https://github.com/Scooletz/QueueBatch/pull/16#discussion_r249238562>:
>
> > @@ -26,7 +96,9 @@ public async Task Simple_batch_dispatch()
>
>
>
>          public class SimpleBatchDispatch
>
>          {
>
> -            public static async Task Do([QueueBatchTrigger(InputQueue, ParallelGets = 2, MaxBackOffInSeconds = 30)] IMessageBatch batch, [Queue(OutputQueue)] CloudQueue output)
>
> +            public static async Task Do(
>
>
> Is it autoformatting applied here? I can see that some signatures were
> changed in a similar way.
> ------------------------------
>
> In src/QueueBatch/Impl/Listener.cs
> <https://github.com/Scooletz/QueueBatch/pull/16#discussion_r249238575>:
>
> > @@ -17,6 +17,7 @@ class Listener : IListener
>
>          readonly int maxRetries;
>
>          readonly QueueFunctionLogic queue;
>
>          readonly TimeSpan visibilityTimeout;
>
> +        private readonly bool successOrFailAsBatch;
>
>
> ⬇️ Suggested change
>
> -        private readonly bool successOrFailAsBatch;
>
> +        readonly bool successOrFailAsBatch;
>
>
> ------------------------------
>
> In src/QueueBatch/QueueBatchTriggerAttribute.cs
> <https://github.com/Scooletz/QueueBatch/pull/16#discussion_r249238601>:
>
> > @@ -52,5 +52,10 @@ public QueueBatchTriggerAttribute(string queueName)
>
>          /// Gets or sets the app setting name that contains the Azure Storage connection string.
>
>          /// </summary>
>
>          public string Connection { get; set; }
>
> +
>
> +        /// <summary>
>
> +        /// If set to false, each message in same batch can be marked as processed independently and they will not affected when other messages cause exception, default to true
>
> +        /// </summary>
>
> +        public bool SuccessOrFailAsBatch { get; set; } = true;
>
>
> Nice. With this default we can ship it as a minor.
> ------------------------------
>
> In src/QueueBatch.Tests/Helpers.cs
> <https://github.com/Scooletz/QueueBatch/pull/16#discussion_r249238611>:
>
> > @@ -39,7 +39,7 @@ public static async Task<List<CloudQueueMessage>> Drain(this CloudQueue queue, i
>
>
>
>              return received;
>
>          }
>
> -
>
> +
>
>
> ⬇️ Suggested change
>
> -
>
>
> ------------------------------
>
> In README.md
> <https://github.com/Scooletz/QueueBatch/pull/16#discussion_r249238617>:
>
> > @@ -35,10 +35,10 @@ public static void MyFunc([QueueBatchTrigger("myqueue")] IMessageBatch batch)
>
>  }
>
>  ```
>
>
>
> -You can also acknowledge only some of the messages. The rest, will be retried in a similar manner to the regural `[QueueTrigger]`
>
> +With `SuccessOrFailAsBatch` set to `false`, you can also acknowledge only some of the messages. The rest, will be retried in a similar manner to the regural `[QueueTrigger]`
>
>
> Nice!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Scooletz/QueueBatch/pull/16#pullrequestreview-194349231>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACO9hSzQD9xxwvU7JZkMxPE8MPnV9Qivks5vEtbhgaJpZM4Z3CAZ>
> .
>

2019-01-20 20:45 UTC, jeremy001181 commented
@Scooletz have made changes according to the review let me know if anything else require change

2019-02-18 10:22 UTC, Scooletz commented
@jeremy001181 Sorry for the delay, but due to personal life events, I need to postpone work on this for at least 1-2 weeks more.

2019-05-07 19:11 UTC, Scooletz approved these changes

2019-05-07 19:12 UTC, merged