Connection setting handling
Scooletz/QueueBatch pull request #6
Opened 2018-11-24 20:47 UTC by krlm

This PR adds handling of connection setting of queue storage in a similar way as it's done by regular `QueueTrigger`.

2018-11-25 20:05 UTC, Scooletz requested changes
Awesome stuff 🥇 
If we could clarify a few items, it'd be great.

2018-11-25 20:05 UTC, Scooletz commented on src/QueueBatch.Tests/BaseTest.cs
> +        readonly CloudStorageAccount storageAccount;
`storageAccount` is never used again. Why it is extracted as a field? Previous version had it inlined.

2018-11-25 20:05 UTC, Scooletz commented on src/QueueBatch/Impl/BindingProvider.cs
> +        public BindingProvider(ILoggerFactory loggerFactory, StorageAccountProvider storageAccountProvider,
`StorageAccountProvider` has a simple API that obtains an account from the passed name. Would you consider extracting it to `QueueBatch` instead of referencing `Microsoft.Azure.WebJobs.Extensions.Storage`  for this only? Have you considered it?

2018-11-25 20:05 UTC, Scooletz commented on src/QueueBatch/Impl/BindingProvider.cs
> +            return nameResolver.ResolveWholeString(queueName);
As far as I see, this adds a new functionality of using custom expressions for queue names. Is it required for handling different accounts, or maybe it's provided to mimic `Storage` behavior? If the second, I'd prefer to keep it out of this PR.

2018-11-25 20:05 UTC, Scooletz commented on src/QueueBatch/QueueBatch.csproj
> +    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.0" />
Mentioned in the comment above.

2018-11-25 20:05 UTC, Scooletz commented on src/QueueBatch/QueueBatchTriggerAttribute.cs
> +        public string Connection { get; set; }
Would it be possible to document it in the Readme.md somehow? So far all the properties have their own sections.

2018-11-26 21:25 UTC, krlm commented on src/QueueBatch/Impl/BindingProvider.cs
> +        public BindingProvider(ILoggerFactory loggerFactory, StorageAccountProvider storageAccountProvider,
Yes, I've  noticed that class is quite small and thought about extracting it but wasn't sure if other stuff from `Storage.Extension` will be needed, so finally kept that dependency. However, I completely understand that you'd like to minimize dependency footprint. I'll rewrite it.

2018-11-26 21:27 UTC, krlm commented on src/QueueBatch/Impl/BindingProvider.cs
> +            return nameResolver.ResolveWholeString(queueName);
Yes, this just handles `binding expressions` for queue name. It's not necessary for handling separate storage but allows you to configure queue name from external configuration (file/env.var). Otherwise you're forced to hardcode queue name. (or there's another way?)

2018-11-26 21:28 UTC, krlm commented on src/QueueBatch/QueueBatchTriggerAttribute.cs
> +        public string Connection { get; set; }
Sure.

2018-11-26 21:28 UTC, krlm commented on src/QueueBatch.Tests/BaseTest.cs
> +        readonly CloudStorageAccount storageAccount;
My bad, didn't clean up properly.

2018-11-26 22:26 UTC, krlm commented on src/QueueBatch/Impl/BindingProvider.cs
> +            return nameResolver.ResolveWholeString(queueName);
I removed that change from here. Let me know if you'd consider accepting this feature as a separate PR.

2018-11-27 09:29 UTC, Scooletz commented on src/QueueBatch/Impl/BindingProvider.cs
> +        public BindingProvider(ILoggerFactory loggerFactory, StorageAccountProvider storageAccountProvider,
Great 😍

2018-11-27 09:38 UTC, Scooletz commented on src/QueueBatch/Impl/BindingProvider.cs
> +            return nameResolver.ResolveWholeString(queueName);
Yes, I see the value of having it resolved, not hard-coded. Of course I'd be happy to accept it as a separate PR.

2018-11-27 09:39 UTC, Scooletz commented on src/QueueBatch/QueueBatchTriggerAttribute.cs
> +        public string Connection { get; set; }
Resolved in the next commit.

2018-11-28 07:47 UTC, krlm commented
@Scooletz I've fixed all of above issues. Am I supposed to mark those conversations as resolved or just wait for further review? (I'm not really familiar with github reviews workflow)

2018-11-28 22:00 UTC, Scooletz commented
Nope. Let me review it tomorrow in the morning, rerun the tests, etc. Once I'm done, I'll merge it.

Thank you again for introducing this feature 🤗

2018-11-29 06:56 UTC, Scooletz commented
@krlm I added a few minor fixes in here: https://github.com/krlm/QueueBatch/pull/1 If you could accept it (squash-merge) preferred, I'd accept this one. Maybe I could have propose all the changes in here, but it was easier for me to get this as a PR for your PR.

2018-11-29 19:57 UTC, Scooletz approved these changes

2018-11-29 19:57 UTC, Scooletz commented
Thank you @krlm  for bringing it! 🤗

2018-11-29 19:58 UTC, merged